---
- name: install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: 'True'
    cache_valid_time: 3600
  tags:
    - dnsmasq

- name: put dnsmasq config
  copy:
    content: |
      server=/consul/127.0.0.1#8600
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  tags:
    - dnsmasq

- name: enable dnsmasq
  service:
    name: dnsmasq
    enabled: 'True'
  tags:
    - dnsmasq
