---
- name: install dependencies
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  tags:
    - install

- name: install consul
  unarchive:
    src: "{{ consul_src }}"
    dest: "{{ consul_dest }}"
    mode: 0755
    remote_src: yes
  tags:
    - install

- name: ensure consul run directory
  file:
    path: "{{ consul_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- name: ensure consul run data directory
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- name: ensure consul config directory
  file:
    path: "{{ consul_conf_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - install

- assert:
    that:
      - 'consul_mode in ("client", "server")'

- name: Gather facts
  ec2_facts:
  tags:
    - configuration

- set_fact:
    consul_datacenter: "{{ ansible_ec2_placement_region }}"
  tags:
    - configuration

- name: put consul configuration
  template:
    src: "{{ consul_mode }}.json.j2"
    dest: /etc/consul.d/config.json
    owner: root
    group: root
    mode: 0644
  register: consul_conf
  tags:
    - configuration

- name: put systemd configuration
  template:
    src: "{{ consul_mode }}.service.j2"
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644

- name: enable consul
  service:
    name: consul
    enabled: yes
  tags:
    - configuration
