---
- name: Gather facts
  ec2_facts:
  tags:
    - configuration

- set_fact:
    consul_datacenter: "{{ ansible_ec2_placement_region }}"
  tags:
    - configuration

- name: put consul server configuration
  template:
    src: server.json.j2
    dest: /etc/consul.d/server.json
    owner: root
    group: root
    mode: 0644
  register: consul_conf
  tags:
    - configuration

- name: put systemd configuration
  template:
    src: server.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644

- name: enable consul
  service:
    name: consul
    enabled: yes
  tags:
    - configuration
