---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  when: consul_service_started and lookup('env', 'MOLECULE_DRIVER_NAME') != 'docker'


- name: restart consul
  service:
    name: consul
    state: restarted
  when: consul_service_started and lookup('env', 'MOLECULE_DRIVER_NAME') != 'docker'
